### ISSUE TITLE
Add some statements/facts.

### ISSUE THREAD

**Issue by Xabifk** [Xabifk/facts-and-statements#2]
## More data is needed
* Add something to this repo. It doesn't matter if it seems simple, more is better in this case.

* Just don't add duplicates and try to keep it _**simple**_

**Comment by bg-s-25** [comment]
Hi. I could work on getting some more statements in (Participating in Hacktoberfest)

**Comment by tnoeding** [comment]
Hello, I'll add some items for "A".
